// Example: Comprehensive Response Types with Oxidite

use oxidite::prelude::*;
use serde::Deserialize;

#[derive(Deserialize)]
struct QueryParams {
    format: Option<String>,
}

// JSON response example
async fn api_endpoint(_req: Request) -> Result<Response> {
    Ok(Response::json(serde_json::json!({
        "message": "Hello from API",
        "timestamp": chrono::Utc::now().to_rfc3339(),
        "framework": "Oxidite",
        "version": "2.0"
    })))
}

// HTML response example
async fn html_page(_req: Request) -> Result<Response> {
    let html_content = r#"
    <!DOCTYPE html>
    <html>
    <head>
        <title>Oxidite Example</title>
        <style>
            body { font-family: Arial, sans-serif; margin: 40px; }
            .container { max-width: 800px; margin: 0 auto; }
        </style>
    </head>
    <body>
        <div class="container">
            <h1>Welcome to Oxidite!</h1>
            <p>This is an HTML response generated by Oxidite.</p>
            <ul>
                <li><a href="/">Text Response</a></li>
                <li><a href="/api">JSON Response</a></li>
                <li><a href="/empty">Empty Response</a></li>
                <li><a href="/error">Error Response</a></li>
            </ul>
        </div>
    </body>
    </html>
    "#;
    
    Ok(Response::html(html_content.to_string()))
}

// Text response example
async fn text_response(_req: Request) -> Result<Response> {
    Ok(Response::text("This is a plain text response from Oxidite!".to_string()))
}

// Empty response example
async fn empty_response(_req: Request) -> Result<Response> {
    Ok(Response::ok())
}

// Error response example
async fn error_response(_req: Request) -> Result<Response> {
    Err(Error::BadRequest("This is a sample error response".to_string()))
}

// Conditional response based on query parameter
async fn conditional_response(Query(params): Query<QueryParams>) -> Result<Response> {
    match params.format.as_deref() {
        Some("json") => Ok(Response::json(serde_json::json!({ "format": "json", "message": "JSON response" }))),
        Some("html") => Ok(Response::html("<h1>HTML Response</h1><p>Format: HTML</p>".to_string())),
        Some("text") => Ok(Response::text("Text Response\nFormat: TEXT".to_string())),
        _ => Ok(Response::json(serde_json::json!({ 
            "format": "default", 
            "message": "Default JSON response",
            "available_formats": ["json", "html", "text"]
        })))
    }
}

// Example with path parameters
async fn user_profile(Path(user_id): Path<u32>) -> Result<Response> {
    Ok(Response::json(serde_json::json!({
        "user_id": user_id,
        "name": format!("User {}", user_id),
        "email": format!("user{}@example.com", user_id),
        "active": true
    })))
}

// Example with cookies
async fn cookie_demo(cookies: Cookies) -> Result<Response> {
    let session_id = cookies.get("session_id").unwrap_or("no-session");
    let theme = cookies.get("theme").unwrap_or("default");
    
    Ok(Response::json(serde_json::json!({
        "session_id": session_id,
        "theme": theme,
        "cookies_received": cookies.iter().count()
    })))
}

#[tokio::main]
async fn main() -> Result<()> {
    let mut router = Router::new();
    
    // Basic responses
    router.get("/", text_response);
    router.get("/api", api_endpoint);
    router.get("/html", html_page);
    router.get("/empty", empty_response);
    router.get("/error", error_response);
    
    // Conditional response
    router.get("/conditional", conditional_response);
    
    // Path parameter example
    router.get("/users/:id", user_profile);
    
    // Cookie example
    router.get("/cookies", cookie_demo);
    
    let server = Server::new(router);
    println!("Comprehensive Response Types Example Server");
    println!("Visit:");
    println!("  http://127.0.0.1:3000/ - Plain text response");
    println!("  http://127.0.0.1:3000/api - JSON response");
    println!("  http://127.0.0.1:3000/html - HTML response");
    println!("  http://127.0.0.1:3000/empty - Empty response");
    println!("  http://127.0.0.1:3000/error - Error response");
    println!("  http://127.0.0.1:3000/conditional - Conditional response");
    println!("  http://127.0.0.1:3000/conditional?format=json - JSON format");
    println!("  http://127.0.0.1:3000/conditional?format=html - HTML format");
    println!("  http://127.0.0.1:3000/conditional?format=text - Text format");
    println!("  http://127.0.0.1:3000/users/127 - Path parameter example");
    println!("  http://127.0.0.1:3000/cookies - Cookie example (add cookies to test)");
    
    server.listen("127.0.0.1:3000".parse().unwrap()).await
}