//! Database migration system

use chrono::Utc;
use sqlx::Row;
use std::fs;
use std::path::{Path, PathBuf};
use thiserror::Error;

pub type MigrationResult<T> = std::result::Result<T, MigrationError>;

#[derive(Debug, Error)]
pub enum MigrationError {
    #[error(transparent)]
    Io(#[from] std::io::Error),
    #[error(transparent)]
    Database(#[from] sqlx::Error),
    #[error("invalid migration filename `{filename}`")]
    InvalidFilename { filename: String },
}

/// Migration file
#[derive(Debug)]
pub struct Migration {
    pub version: String,
    pub name: String,
    pub up_sql: String,
    pub down_sql: String,
}

impl Migration {
    pub fn new(name: &str) -> Self {
        let timestamp = Utc::now().format("%Y%m%d%H%M%S").to_string();
        let version = format!("{}_{}", timestamp, name);

        Self {
            version,
            name: name.to_string(),
            up_sql: String::new(),
            down_sql: String::new(),
        }
    }

    pub fn from_file(path: impl AsRef<Path>) -> Result<Self, std::io::Error> {
        Self::from_file_checked(path).map_err(|err| match err {
            MigrationError::Io(io) => io,
            other => std::io::Error::new(std::io::ErrorKind::InvalidData, other.to_string()),
        })
    }

    pub fn from_file_checked(path: impl AsRef<Path>) -> MigrationResult<Self> {
        let path = path.as_ref();
        let content = fs::read_to_string(path)?;

        let filename = path.file_stem().and_then(|s| s.to_str()).ok_or_else(|| {
            MigrationError::InvalidFilename {
                filename: path.display().to_string(),
            }
        })?;

        // Parse filename: 20240101120000_create_users
        let parts: Vec<&str> = filename.splitn(2, '_').collect();
        if parts.len() != 2 {
            return Err(MigrationError::InvalidFilename {
                filename: filename.to_string(),
            });
        }

        let version = filename.to_string();
        let name = parts[1].to_string();

        // Split content into up/down SQL
        let sections: Vec<&str> = content.split("-- migrate:down").collect();
        let up_sql = sections
            .get(0)
            .unwrap_or(&"")
            .replace("-- migrate:up", "")
            .trim()
            .to_string();
        let down_sql = sections.get(1).unwrap_or(&"").trim().to_string();

        Ok(Self {
            version,
            name,
            up_sql,
            down_sql,
        })
    }

    pub fn save(&self, migrations_dir: impl AsRef<Path>) -> Result<PathBuf, std::io::Error> {
        let migrations_dir = migrations_dir.as_ref();
        fs::create_dir_all(migrations_dir)?;

        let filename = format!("{}.sql", self.version);
        let path = migrations_dir.join(filename);

        let content = format!(
            "-- Generated by `oxidite generate migration {name}`.\n-- Write the forward change below. Keep each SQL statement terminated with a semicolon.\n-- migrate:up\n{up}\n\n-- Write the rollback that undoes the change below.\n-- If a rollback is unsafe, explain it here before the SQL.\n-- migrate:down\n{down}\n",
            name = self.name,
            up = self.up_sql,
            down = self.down_sql
        );

        fs::write(&path, content)?;
        Ok(path)
    }
}

/// Migration manager
pub struct MigrationManager {
    migrations_dir: PathBuf,
}

impl MigrationManager {
    pub fn new(migrations_dir: impl AsRef<Path>) -> Self {
        Self {
            migrations_dir: migrations_dir.as_ref().to_path_buf(),
        }
    }

    pub fn list_migrations(&self) -> Result<Vec<Migration>, std::io::Error> {
        self.list_migrations_checked().map_err(|err| match err {
            MigrationError::Io(io) => io,
            other => std::io::Error::new(std::io::ErrorKind::InvalidData, other.to_string()),
        })
    }

    pub fn list_migrations_checked(&self) -> MigrationResult<Vec<Migration>> {
        let mut migrations = Vec::new();

        if !self.migrations_dir.exists() {
            return Ok(migrations);
        }

        for entry in fs::read_dir(&self.migrations_dir)? {
            let entry = entry?;
            let path = entry.path();

            if path.is_file() && path.extension().and_then(|s| s.to_str()) == Some("sql") {
                let migration = Migration::from_file_checked(&path)?;
                migrations.push(migration);
            }
        }

        // Sort by version
        migrations.sort_by(|a, b| a.version.cmp(&b.version));

        Ok(migrations)
    }

    pub fn create_migration(&self, name: &str) -> Result<PathBuf, std::io::Error> {
        self.create_migration_checked(name)
            .map_err(|err| match err {
                MigrationError::Io(io) => io,
                other => std::io::Error::new(std::io::ErrorKind::InvalidData, other.to_string()),
            })
    }

    pub fn create_migration_checked(&self, name: &str) -> MigrationResult<PathBuf> {
        let migration = Migration::new(name);
        Ok(migration.save(&self.migrations_dir)?)
    }

    /// Ensure migrations table exists
    pub async fn ensure_migrations_table(&self, db: &impl crate::Database) -> crate::Result<()> {
        let sql = match db.db_type() {
            crate::DatabaseType::Sqlite => {
                r#"
                CREATE TABLE IF NOT EXISTS _migrations (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    version TEXT NOT NULL UNIQUE,
                    applied_at INTEGER NOT NULL
                )
                "#
            }
            crate::DatabaseType::Postgres => {
                r#"
                CREATE TABLE IF NOT EXISTS _migrations (
                    id BIGSERIAL PRIMARY KEY,
                    version TEXT NOT NULL UNIQUE,
                    applied_at BIGINT NOT NULL
                )
                "#
            }
            crate::DatabaseType::MySql => {
                r#"
                CREATE TABLE IF NOT EXISTS _migrations (
                    id BIGINT AUTO_INCREMENT PRIMARY KEY,
                    version VARCHAR(255) NOT NULL UNIQUE,
                    applied_at BIGINT NOT NULL
                )
                "#
            }
        };
        db.execute(sql).await?;
        Ok(())
    }

    /// Get list of applied migrations
    pub async fn get_applied_migrations(
        &self,
        db: &impl crate::Database,
    ) -> crate::Result<Vec<String>> {
        self.ensure_migrations_table(db).await?;

        let rows = db
            .query("SELECT version FROM _migrations ORDER BY version")
            .await?;
        let mut versions = Vec::new();

        for row in rows {
            if let Ok(version) = row.try_get::<String, _>("version") {
                versions.push(version);
            }
        }

        Ok(versions)
    }

    /// Mark migration as applied
    pub async fn mark_migration_applied(
        &self,
        db: &impl crate::Database,
        version: &str,
    ) -> crate::Result<()> {
        self.ensure_migrations_table(db).await?;

        let timestamp = chrono::Utc::now().timestamp();
        let query = sqlx::query("INSERT INTO _migrations (version, applied_at) VALUES (?, ?)")
            .bind(version)
            .bind(timestamp);
        db.execute_query(query).await?;
        Ok(())
    }

    /// Remove migration record (for rollback)
    pub async fn mark_migration_reverted(
        &self,
        db: &impl crate::Database,
        version: &str,
    ) -> crate::Result<()> {
        let query = sqlx::query("DELETE FROM _migrations WHERE version = ?").bind(version);
        db.execute_query(query).await?;
        Ok(())
    }

    /// Get pending migrations
    pub async fn get_pending_migrations(
        &self,
        db: &impl crate::Database,
    ) -> Result<Vec<Migration>, Box<dyn std::error::Error>> {
        Ok(self.get_pending_migrations_checked(db).await?)
    }

    pub async fn get_pending_migrations_checked(
        &self,
        db: &impl crate::Database,
    ) -> MigrationResult<Vec<Migration>> {
        let all_migrations = self.list_migrations_checked()?;
        let applied = self.get_applied_migrations(db).await?;

        let pending: Vec<Migration> = all_migrations
            .into_iter()
            .filter(|m| !applied.contains(&m.version))
            .collect();

        Ok(pending)
    }
}

#[cfg(test)]
mod tests {
    use super::{Migration, MigrationManager};
    use crate::{sqlx, Database, DatabaseType, DbTransaction, Result};
    use async_trait::async_trait;
    use sqlx::any::AnyRow;
    use std::sync::Arc;
    use tokio::sync::Mutex;

    #[derive(Debug, Clone)]
    struct MockDb {
        db_type: DatabaseType,
        executed_sql: Arc<Mutex<Vec<String>>>,
    }

    impl MockDb {
        fn new(db_type: DatabaseType) -> Self {
            Self {
                db_type,
                executed_sql: Arc::new(Mutex::new(Vec::new())),
            }
        }

        async fn last_sql(&self) -> Option<String> {
            self.executed_sql.lock().await.last().cloned()
        }
    }

    #[async_trait]
    impl Database for MockDb {
        fn db_type(&self) -> DatabaseType {
            self.db_type
        }
        async fn execute(&self, query: &str) -> Result<u64> {
            self.executed_sql.lock().await.push(query.to_string());
            Ok(0)
        }
        async fn query(&self, _query: &str) -> Result<Vec<AnyRow>> {
            Ok(vec![])
        }
        async fn query_one(&self, _query: &str) -> Result<Option<AnyRow>> {
            Ok(None)
        }
        async fn ping(&self) -> Result<()> {
            Ok(())
        }
        async fn begin_transaction(&self) -> Result<DbTransaction> {
            unimplemented!()
        }
        async fn execute_query<'q>(
            &self,
            _query: sqlx::query::Query<'q, sqlx::Any, sqlx::any::AnyArguments<'q>>,
        ) -> Result<u64> {
            Ok(0)
        }
        async fn fetch_all<'q>(
            &self,
            _query: sqlx::query::Query<'q, sqlx::Any, sqlx::any::AnyArguments<'q>>,
        ) -> Result<Vec<AnyRow>> {
            Ok(vec![])
        }
        async fn fetch_one<'q>(
            &self,
            _query: sqlx::query::Query<'q, sqlx::Any, sqlx::any::AnyArguments<'q>>,
        ) -> Result<Option<AnyRow>> {
            Ok(None)
        }
    }

    #[tokio::test]
    async fn ensure_migrations_table_uses_backend_specific_sql() {
        let manager = MigrationManager::new("migrations");

        let sqlite = MockDb::new(DatabaseType::Sqlite);
        manager.ensure_migrations_table(&sqlite).await.unwrap();
        assert!(sqlite.last_sql().await.unwrap().contains("AUTOINCREMENT"));

        let postgres = MockDb::new(DatabaseType::Postgres);
        manager.ensure_migrations_table(&postgres).await.unwrap();
        assert!(postgres.last_sql().await.unwrap().contains("BIGSERIAL"));

        let mysql = MockDb::new(DatabaseType::MySql);
        manager.ensure_migrations_table(&mysql).await.unwrap();
        assert!(mysql.last_sql().await.unwrap().contains("AUTO_INCREMENT"));
    }

    #[test]
    fn migration_from_file_checked_rejects_bad_filename() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("badname.sql");
        std::fs::write(
            &path,
            "-- migrate:up\nSELECT 1;\n-- migrate:down\nSELECT 1;",
        )
        .unwrap();

        let err = Migration::from_file_checked(&path).unwrap_err().to_string();
        assert!(err.contains("invalid migration filename"));
    }
}
